name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Checkout project
    
    - uses: Borales/actions-yarn@master
    - name: Yarn install & Build the Docker image
      run:
        yarn install
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
