name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [10.x, 12.x]
 
    steps:
      - name: Checkout project
        uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        run: |
          yarn install
          docker build . --file Dockerfile --tag my-image-name:$(date +%s)
          
          
