name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Yarn install
      run:
        yarn install
        
    - name: Build the Docker image
    - uses: actions/checkout@v1
      run:
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
